# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Use custom format
format = """
[╭─────](bold red)$git_branch$git_status$git_state$fill$mise$fill$aws
[│](bold red)$sudo$status$directory$golang$fill$kubernetes
[╰](bold red)$character"""

# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10

# Disable the newline at the start of the prompt.
add_newline = false

[character]
success_symbol = "[I](bold bg:bright-white fg:#019833)"
error_symbol = "[I](bold bg:black fg:red)"
vimcmd_symbol = "[V](bold bg:#019833 fg:white)"

[fill]
symbol = " "

[aws]
symbol = "🧩"
format = '[$symbol $profile \($region\)]($style)'
force_display = true

[git_branch]
symbol = "🔀"
format = "[$symbol $branch(:$remote_branch)]($style)"

[sudo]
disabled = false
format = "[$symbol]($style) "
symbol = "🔮"

# Will show only when commands fail.
[status]
map_symbol = true
disabled = false
format = "[$symbol $status]($style) "

[golang]
format = "[$symbol ($version)](bold blue)"
symbol = "🪬"
# version_format = "v"

[directory]
truncation_length = 2
style = "bold fg:white"

[kubernetes]
symbol = "🎡"
format = '[$symbol $context@$namespace]($style)'
style = 'purple bold'
disabled = false

[mise]
disabled = false
