# NUT UPS configuration
# CyberPower BR1200ELCD via USB

maxretry = 3

[ups]
  driver = usbhid-ups
  port = auto
  vendorid = 0764
  productid = 0501
  product = BR1200ELCD
  vendor = CPS
  desc = "CyberPower BR1200ELCD"
